dist: trusty
sudo: required
services:
  - docker
git:
  depth: 3
script:
  - docker pull debenham/xlights
  - docker run --name buildvm debenham/xlights /bin/bash Recipe.appimage
after_success:
  - docker cp buildvm:/xLights/xLights/AppImage/ /tmp/
  - ls -lh /tmp/*
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glod: true
  file: /tmp/AppImage/*.AppImage
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    - MAKEFLAGS="-j 2"
notifications:
  email:
    recipients:
      - chris@adebenham.com
      - keithsw1111@hotmail.com
    on_success: never
    on_failure: always
